# Generated by Django 5.0.7 on 2024-07-29 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.EmailField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Assistent'), (2, 'Apotheek'), (3, 'Admin')], null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apotheek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btwNummer', models.CharField(blank=True, max_length=50, null=True)),
                ('btwPlichtig', models.BooleanField(default=True)),
                ('naamBedrijf', models.CharField(blank=True, max_length=200, null=True)),
                ('straatBedrijf', models.CharField(blank=True, max_length=200, null=True)),
                ('huisnummerBedrijf', models.CharField(blank=True, max_length=10, null=True)),
                ('postcodeBedrijf', models.CharField(blank=True, max_length=10, null=True)),
                ('stadBedrijf', models.CharField(blank=True, max_length=200, null=True)),
                ('uurtarief', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assistent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btwNummer', models.CharField(max_length=50)),
                ('btwPlichtig', models.BooleanField(default=True)),
                ('naamBedrijf', models.CharField(max_length=200)),
                ('straatBedrijf', models.CharField(max_length=200)),
                ('huisnummerBedrijf', models.CharField(max_length=10)),
                ('postcodeBedrijf', models.CharField(max_length=10)),
                ('stadBedrijf', models.CharField(max_length=200)),
                ('krijgtKilometervergoeding', models.BooleanField(default=True)),
                ('uurtarief', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
