# Generated by Django 5.0.7 on 2024-07-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apotheek',
            old_name='btwNummer',
            new_name='apotheek_btwNummer',
        ),
        migrations.RenameField(
            model_name='apotheek',
            old_name='btwPlichtig',
            new_name='apotheek_btwPlichtig',
        ),
        migrations.RenameField(
            model_name='apotheek',
            old_name='huisnummerBedrijf',
            new_name='apotheek_huisnummerBedrijf',
        ),
        migrations.RenameField(
            model_name='apotheek',
            old_name='naamBedrijf',
            new_name='apotheek_naamBedrijf',
        ),
        migrations.RenameField(
            model_name='apotheek',
            old_name='postcodeBedrijf',
            new_name='apotheek_postcodeBedrijf',
        ),
        migrations.RenameField(
            model_name='apotheek',
            old_name='stadBedrijf',
            new_name='apotheek_stadBedrijf',
        ),
        migrations.RenameField(
            model_name='apotheek',
            old_name='straatBedrijf',
            new_name='apotheek_straatBedrijf',
        ),
        migrations.RenameField(
            model_name='apotheek',
            old_name='uurtarief',
            new_name='apotheek_uurtarief',
        ),
        migrations.RenameField(
            model_name='assistent',
            old_name='btwNummer',
            new_name='assistent_btwNummer',
        ),
        migrations.RenameField(
            model_name='assistent',
            old_name='btwPlichtig',
            new_name='assistent_btwPlichtig',
        ),
        migrations.RenameField(
            model_name='assistent',
            old_name='huisnummerBedrijf',
            new_name='assistent_huisnummerBedrijf',
        ),
        migrations.RenameField(
            model_name='assistent',
            old_name='krijgtKilometervergoeding',
            new_name='assistent_krijgtKilometervergoeding',
        ),
        migrations.RenameField(
            model_name='assistent',
            old_name='naamBedrijf',
            new_name='assistent_naamBedrijf',
        ),
        migrations.RenameField(
            model_name='assistent',
            old_name='postcodeBedrijf',
            new_name='assistent_postcodeBedrijf',
        ),
        migrations.RenameField(
            model_name='assistent',
            old_name='stadBedrijf',
            new_name='assistent_stadBedrijf',
        ),
        migrations.RenameField(
            model_name='assistent',
            old_name='straatBedrijf',
            new_name='assistent_straatBedrijf',
        ),
        migrations.RenameField(
            model_name='assistent',
            old_name='uurtarief',
            new_name='assistent_uurtarief',
        ),
    ]
