# Generated by Django 5.0.7 on 2024-07-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_btwnummer_apotheek_apotheek_btwnummer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apotheek',
            name='apotheek_uurtarief',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='assistent',
            name='assistent_btwNummer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assistent',
            name='assistent_huisnummerBedrijf',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assistent',
            name='assistent_naamBedrijf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assistent',
            name='assistent_postcodeBedrijf',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assistent',
            name='assistent_stadBedrijf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assistent',
            name='assistent_straatBedrijf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='assistent',
            name='assistent_uurtarief',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
