# Generated by Django 5.0.7 on 2024-08-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apotheek',
            name='apotheek_uurtarief',
        ),
        migrations.RemoveField(
            model_name='assistent',
            name='assistent_krijgtKilometervergoeding',
        ),
        migrations.RemoveField(
            model_name='assistent',
            name='assistent_uurtarief',
        ),
    ]
