# Generated by Django 5.0.7 on 2024-08-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_apotheek_apotheek_uurtarief_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistent',
            name='assistent_rekeningnummer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
