# Generated by Django 5.0.7 on 2024-08-02 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone_number'),
        ('calendar_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='apotheek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apotheekevents', to='accounts.apotheek'),
        ),
        migrations.AddField(
            model_name='event',
            name='assistent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistentevents', to='accounts.assistent'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('werk', 'Werk'), ('opleiding', 'Opleiding'), ('teambuilding', 'Teambuilding'), ('overleg', 'Overleg')], default='werk', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userevents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('werk', 'Werk'), ('opleiding', 'Opleiding'), ('teambuilding', 'Teambuilding'), ('overleg', 'Overleg')], default='noaction', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='status_last_changed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
