# Generated by Django 5.0.7 on 2024-08-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_event_apotheek_event_assistent_event_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('accepted', 'Goedgekeurd'), ('noaction', 'Geen actie'), ('declined', 'Afgekeurd')], default='noaction', max_length=50),
        ),
    ]
