# Generated by Django 5.0.7 on 2024-08-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_remove_event_description_remove_event_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gewerkte_uren',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
