# Generated by Django 5.0.7 on 2024-08-05 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_event_gewerkte_uren'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gewerkte_uren',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
