# Generated by Django 5.0.7 on 2024-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_alter_event_gewerkte_uren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gewerkte_uren',
        ),
        migrations.AddField(
            model_name='event',
            name='pauzeduur',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
