# Generated by Django 5.0.7 on 2024-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_remove_event_gewerkte_uren_event_pauzeduur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='status_last_changed_date',
        ),
        migrations.AddField(
            model_name='event',
            name='status_apotheek',
            field=models.CharField(choices=[('accepted', 'Goedgekeurd'), ('noaction', 'Geen actie'), ('declined', 'Afgekeurd')], default='noaction', max_length=50),
        ),
    ]
