# Generated by Django 5.0.7 on 2024-08-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_event_status_apotheek_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
