# Generated by Django 5.0.7 on 2024-08-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_event_invoiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invoiced_to_apotheek',
            field=models.BooleanField(default=False),
        ),
    ]
