# Generated by Django 5.0.7 on 2024-08-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_event_invoiced_to_apotheek'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='paid_by_apotheek',
            field=models.BooleanField(default=True),
        ),
    ]
