# Generated by Django 5.0.7 on 2024-08-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0011_event_paid_by_apotheek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='paid_by_apotheek',
            field=models.BooleanField(default=False),
        ),
    ]
