# Generated by Django 5.0.7 on 2024-08-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkbetweenassistentandapotheek',
            old_name='uurtarief',
            new_name='uurtariefAssistent',
        ),
        migrations.AddField(
            model_name='linkbetweenassistentandapotheek',
            name='uurtariefApotheek',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
