# Generated by Django 5.0.7 on 2024-08-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_rename_uurtarief_linkbetweenassistentandapotheek_uurtariefassistent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkbetweenassistentandapotheek',
            name='actief',
            field=models.BooleanField(default=True),
        ),
    ]
