# Generated by Django 5.0.7 on 2024-08-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_linkbetweenassistentandapotheek_actief'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkbetweenassistentandapotheek',
            old_name='fietsvergoeding',
            new_name='kilometervergoeding',
        ),
    ]
