# Generated by Django 5.0.7 on 2024-08-20 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_apotheek_apotheek_uurtarief_and_more'),
        ('invoice', '0004_rename_fietsvergoeding_linkbetweenassistentandapotheek_kilometervergoeding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('invoice_created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_amount', models.FloatField()),
                ('invoice_paid', models.BooleanField(default=False)),
                ('invoice_paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.assistent')),
                ('invoice_paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overview of invoice',
                'verbose_name_plural': 'Overview of invoices',
                'unique_together': {('invoice_number', 'invoice_created_by')},
            },
        ),
    ]
