# Generated by Django 5.0.7 on 2024-08-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0012_alter_event_paid_by_apotheek'),
        ('invoice', '0005_invoiceoverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_subtotal', models.FloatField(default=0.0)),
                ('invoice_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.event')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoiceoverview')),
            ],
        ),
    ]
