# Generated by Django 5.0.7 on 2024-08-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceoverview',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
