# Generated by Django 5.0.7 on 2024-08-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoiceoverview_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceoverview',
            name='invoice_btw',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
