# Generated by Django 5.0.7 on 2024-08-27 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0012_alter_event_paid_by_apotheek'),
        ('invoice', '0008_invoiceoverview_invoice_btw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceoverview',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/assistent/'),
        ),
        migrations.CreateModel(
            name='InvoiceApotheekOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('invoice_created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_amount', models.FloatField()),
                ('invoice_btw', models.FloatField()),
                ('invoice_paid', models.BooleanField(default=False)),
                ('invoice_paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='invoices/apotheek/')),
                ('invoice_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_created_by', to=settings.AUTH_USER_MODEL)),
                ('invoice_paid_status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_paid_status_changed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overview of invoice',
                'verbose_name_plural': 'Overview of invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceApotheekDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_subtotal', models.FloatField(default=0.0)),
                ('invoice_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.event')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoiceapotheekoverview')),
            ],
        ),
    ]
