# Generated by Django 5.0.7 on 2024-08-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_assistent_assistent_rekeningnummer'),
        ('invoice', '0009_alter_invoiceoverview_invoice_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceapotheekoverview',
            name='invoice_apotheek',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.apotheek'),
            preserve_default=False,
        ),
    ]
